<?php
$this->mainMenu()->setActiveItemId('stravabeheer');
$this->pageBreadcrumbs()->setLayout('beheer');
$this->pageBreadcrumbs()->setItems([
    'Beheer' => $this->url('beheer'),
    'Strava' => $this->url('strava'),
]);
?>
<!-- Page Header -->
<div class="row">
    <h1 class="col">DETAIL</h1>
</div>
<!-- Breadcrumbs -->
<div class="row">
    <div class="col">
        <?= $this->pageBreadcrumbs()->render(); ?>
    </div>
</div>
<div class="row">
    <div class="col">

        <table class="table table-dark table-sm table-bordered table-hover table-striped">
            <thead class="thead-dark">
            <tr>
                <th class="text-center"><i class="fas fa-flag-checkered"> / <i class="fas fa-dumbbell"></i></th>
                <th>Datum</th>
                <th>Naam</th>
                <th>Afstand</th>
                <th>Tijd</th>
                <th>Hoogte</th>
                <th class="text-center"><i class="fas fa-cogs"></i></th>
            </tr>
            </thead>
            <tbody>
                <tr <?= ($activity["workout_type"] == 1? 'class="bg-success"':''); ?>>
                    <td class="text-center">
                        <?= ($activity["workout_type"] == 1? '<i class="fas fa-flag-checkered"></i>':''); ?>
                        <?= ($activity["workout_type"] == 3? '<i class="fas fa-dumbbell"></i>':''); ?>
                    </td>
                    <td><?= $activity["start_date"]; ?></td>
                    <td><?= $activity["name"]; ?></td>
                    <td><?= number_format($activity["distance"] / 1000, 2, ',', '.'); ?> km</td>
                    <td><?= number_format($activity["moving_time"] / 60, 2, ':', ''); ?></td>
                    <td><?= number_format($activity["total_elevation_gain"], 1, ',', ''); ?></td>
                    <td class="text-center">
                        <a class="btn btn-sm btn-secondary" title="Edit event" href="<?= $this->url('strava', ['action' => 'detail', 'id' => $activity["id"]]); ?>">
                            <i class="fas fa-edit"></i>
                        </a>
                    </td>
                </tr>
            <tr>
                <td colspan="7">
                    <iframe src="https://maps.googleapis.com/maps/api/staticmap?size=600x300&maptype=roadmap&path=enc:<?= $activity["map"]["polyline"] ?>&key=AIzaSyDphZyrqkSNlFDwuWOCMGnzLF39L8g_nlw"></iframe>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>