<?php
$this->mainMenu()->setActiveItemId('stravabeheer');
$this->pageBreadcrumbs()->setLayout('beheer');
$this->pageBreadcrumbs()->setItems([
    'Beheer' => $this->url('beheer'),
    'Strava' => $this->url('strava'),
]);
?>
<!-- Page Header -->
<div class="row">
    <h1 class="col">STRAVA BEHEER</h1>
</div>
<!-- Breadcrumbs -->
<div class="row">
    <div class="col">
        <?= $this->pageBreadcrumbs()->render(); ?>
    </div>
</div>
<div id="stravaOverview" class="row">
    <div class="col">
        <div class="card bg-success">
            <div class="card-header text-center">
                <i class="fa fa-running"></i>
            </div>
            <div class="card-body">
                <h5 class="card-title text-center"><?= $totalRunActivities ?></h5>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card bg-warning">
            <div class="card-header text-center">
                <i class="fas fa-tachometer-alt"></i>
            </div>
            <div class="card-body">
                <h5 class="card-title text-center"><?= $averageSpeed ?></h5>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card bg-secondary">
            <div class="card-header text-center">
                <i class="fas fa-road"></i>
            </div>
            <div class="card-body">
                <h5 class="card-title text-center">
                    <?= number_format($totalRunDistance / 1000, 2, ',', '.'); ?>
                   </h5>
            </div>
        </div>
    </div>
</div>