<div id="stravaOverview" class="container-fluid pt-4 px-4">
    <div class="bg-secondary rounded  p-4">
        <div class="row g-4">
            <div class="col">
                <div class="bg-secondary rounded d-flex align-items-center justify-content-between p-4">
                    <div class="card bg-success">
                        <div class="card-header text-center">
                            <i class="fa fa-running"></i>
                            <h5 class="card-title text-center mt-2">Totaal activiteiten</h5>
                        </div>
                        <div class="card-body">
                            <h5 class="card-title text-center"><?= $totalRunActivities ?></h5>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="bg-secondary rounded d-flex align-items-center justify-content-between p-4">
                    <div class="card bg-info">
                        <div class="card-header text-center">
                            <i class="fas fa-tachometer-alt"></i>
                            <h5 class="card-title text-center mt-2">Gemiddelde tempo</h5>
                        </div>
                        <div class="card-body">
                            <h5 class="card-title text-center">
                                <?= $this->stravaViewHelper()->getAverageSpeed($averageSpeed) ?>
                            </h5>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="bg-secondary rounded d-flex align-items-center justify-content-between p-4">
                    <div class="card bg-primary">
                        <div class="card-header text-center">
                            <i class="fas fa-road"></i>
                            <h5 class="card-title text-center mt-2">Totaal km's</h5>
                        </div>
                        <div class="card-body">
                            <h5 class="card-title text-center">
                                <?= $this->stravaViewHelper()->getDistance($totalRunDistance) ?> km
                            </h5>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="bg-secondary rounded d-flex align-items-center justify-content-between p-4">
                    <div class="card bg-warning">
                        <div class="card-header text-center">
                            <i class="fas fa-stopwatch"></i>
                            <h5 class="card-title text-center mt-2">Totaal tijd</h5>
                        </div>
                        <div class="card-body">
                            <h5 class="card-title text-center">
                                <?= $this->stravaViewHelper()->getTotalMovingTime($totalRunTime); ?>
                            </h5>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="bg-secondary rounded d-flex align-items-center justify-content-between p-4">
                    <div class="card bg-danger">
                        <div class="card-header text-center">
                            <i class="fas fa-mountain"></i>
                            <h5 class="card-title text-center mt-2">Gemid. hoogteverschil</h5>
                        </div>
                        <div class="card-body">
                            <h5 class="card-title text-center">
                                <?= $this->stravaViewHelper()->getTotalElevationGain($averageElevation); ?>
                            </h5>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php
/*
 * Partial for fastest competition run, round and longest run
 */
echo $this->partial('strava-api/partial/competition-stats.phtml',
    [
        'fastestActivity' => $fastestActivity,
        'longestActivity' => $longestActivity,
        'fastestRound' => $fastestRound
    ]
);
/*
 * Partial for fastest training run, round and longest run
 */
echo $this->partial('strava-api/partial/training-stats.phtml',
    [
        'fastestActivity' => $fastestTrainingActivity,
        'longestActivity' => $longestTrainingActivity,
        'fastestRound' => $fastestTrainingRound
    ]
);
?>
<div class="row">
    <div class="col">
        <div class="chart-container" style="position: relative; height:40vh; width:80vw">
            <canvas id="chart"></canvas>
        </div>
    </div>
</div>
<script>
    /* Chatter chart */
    var canvas = document.getElementById('chart');
    var scatterChart = new Chart(canvas, {
        type: 'scatter',
        data: {
            labels: [
                <?php foreach($activities as $activity) { ?>
                "<?= $activity->getName(); ?> (<?= $activity->getStartDate()->format('d-m-Y') ?>)",
                <?php } ?>
            ],
            datasets: [{
                label: 'Scatter Dataset',
                data: [
                    <?php foreach($activities as $activity) { ?>
                    {
                        x: <?= $this->stravaViewHelper()->getDistance($activity->getDistance()) ?>,
                        y: <?= $this->stravaViewHelper()->getAverageSpeedForChart($activity->getAverageSpeed()); ?>
                    },
                    <?php } ?>
                ],
                pointBackgroundColor: [
                    <?php foreach($activities as $activity) { ?>
                    '#' + Math.floor(Math.random() * 16777215).toString(16),
                    <?php } ?>
                ],
                pointHoverBackgroundColor: [
                    <?php foreach($activities as $activity) { ?>
                    '#' + Math.floor(Math.random() * 16777215).toString(16),
                    <?php } ?>
                ],
                fill: false,
                pointHoverRadius: 5,
                backgroundColor: '#FFF'
            }]
        },
        options: {
            tooltips: {
                callbacks: {
                    label: function (tooltipItem, data) {
                        var label = data.labels[tooltipItem.index];
                        return label + ': (' + tooltipItem.xLabel + ', ' + tooltipItem.yLabel + ')';
                    }
                }
            },
            title: {
                display: true,
                text: 'Gemiddelde tempo per activiteit',
                fontSize: 16,
                fontColor: 'white',
                fontFamily: 'Arial, Verdana'
            },
            scales: {
                xAxes: [{
                    type: 'linear',
                    position: 'bottom',
                    ticks: {
                        fontColor: "#FFF"
                    },
                    gridLines: {
                        display: false,
                        color: "#FFFFFF",
                        fontColor: 'white'
                    }
                }],
                yAxes: [{
                    type: 'linear',
                    position: 'bottom',
                    ticks: {
                        fontColor: "#FFF"
                    },
                    gridLines: {
                        display: false,
                        color: "#FFFFFF",
                        fontColor: 'white'
                    }
                }]
            }
        }
    });

    /*
     * Function to resize above div of scatter chart so the page fits well
     */
    function resizeScatterWindow() {
        $('.chart-container').height(scatterChart.chartArea.bottom + 25);
    }

    /*
     * Init function on page load
     */
    resizeScatterWindow();


    $(window).resize(function () {
        if (this.resizeTO) clearTimeout(this.resizeTO);
        this.resizeTO = setTimeout(function () {
            $(this).trigger('resizeEnd');
        }, 500);
    });
    /*
     * Init function on page resize
     */
    $(window).bind('resizeEnd', function () {
        resizeScatterWindow();
    });
</script>