<?php
$this->mainMenu()->setActiveItemId('stravabeheer');
$this->pageBreadcrumbs()->setLayout('beheer');
$this->pageBreadcrumbs()->setItems([
    'Beheer' => $this->url('beheer'),
    'Strava' => $this->url('strava'),
]);
?>
<!-- Page Header -->
<div class="row">
    <h1 class="col">STRAVA BEHEER: authoriseer</h1>
</div>
<!-- Breadcrumbs -->
<div class="row">
    <div class="col">
        <?= $this->pageBreadcrumbs()->render(); ?>
    </div>
</div>
<div class="row">
    <div class="col text-center">
        <p>
            Er zijn nog geen access tokens geregistreerd. Dit betekent dat je eerst de Strava applicatie moet<br/>
            authoriseren om acces tokens te importeren.
        </p>
    </div>
</div>
<div class="row">
    <div class="col text-center">
        <?= '<a class="btn btn-dark" href="' . $authorisationLink . '">Authoriseer Strava</a>' ?>
    </div>
</div>