<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-sm-12 col-md-12 col-xl-12">
            <div class="bg-secondary rounded  p-4">
                <div class="row g-4">
                    <h2 class="col-sm-12 col-md-12 col-xl-12 mb-4">Strava beheer</h2>
                </div>
                <div class="row mb-3">

                    <div class="col-md-auto">
                        <span id="importActivities" class="btn btn-primary">Import <i class="fas fa-upload"></i></span>
                    </div>
                    <div class="col-md">
                        <p>Last import
                            date: <?= (is_object($importLog) && is_object($importLog->getImportDate()) ? $importLog->getImportDate()->format('d-m-Y H:i:s') : ''); ?></p>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <table class="table table-bordered table-hover table-striped">
                            <thead class="thead-primary">
                            <tr>
                                <th class="text-center"><i class="fas fa-hashtag"></i></th>
                                <th class="text-center"><i class="fas fa-flag-checkered"> / <i
                                                class="fas fa-dumbbell"></i></th>
                                <th>Activity Id</th>
                                <th>Datum</th>
                                <th>Naam</th>
                                <th>Afstand</th>
                                <th>Tempo /km</th>
                                <th>Beweegtijd</th>
                                <th>Gem. hartslag</th>
                                <th>Hoogteverschil</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php if (empty($activities)) { ?>
                                <tr>
                                    <td class="text-center" colspan="10">Er zijn geen activiteiten om te uploaden</td>
                                </tr>
                            <?php } else { ?>
                                <?php $nr = 1; ?>
                                <?php foreach ($activities as $index => $activity) { ?>
                                    <tr id="activity-<?= $index ?>" <?= ($activity->workout_type == 1 ? 'class="bg-success"' : ''); ?>>
                                        <td class="text-center">
                                            <?= $nr; ?>
                                            <input type="hidden" value="<?php echo $index; ?>" name="activity"/>
                                        </td>
                                        <td class="text-center">
                                            <?= ($activity->workout_type == 1 ? '<i class="fas fa-flag-checkered"></i>' : ''); ?>
                                            <?= ($activity->workout_type == 3 ? '<i class="fas fa-dumbbell"></i>' : ''); ?>
                                        </td>
                                        <td><?= $index ?></td>
                                        <td><?= $activity->start_date; ?></td>
                                        <td><?= $activity->name; ?></td>
                                        <td><?= $this->stravaViewHelper()->getDistance($activity->distance) ?> km</td>
                                        <td><?= $this->stravaViewHelper()->getAverageSpeed($activity->average_speed); ?></td>
                                        <td><?= $this->stravaViewHelper()->getMovingTime($activity->moving_time); ?></td>
                                        <td><?= $activity->average_heartrate; ?></td>
                                        <td><?= $this->stravaViewHelper()->getTotalElevationGain($activity->total_elevation_gain); ?></td>
                                    </tr>
                                    <?php $nr++; ?>
                                <?php } ?>
                            <?php } ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>