<div class="container-fluid pt-4 px-4">
    <div class="bg-secondary rounded  p-4">
        <div class="row mt-3">
            <h3 class="col text-center">
                Wedstrijd feiten
            </h3>
        </div>
        <div class="row mt-3">
            <div class="col">
                <table class="table table-sm table-bordered table-hover table-striped">
                    <thead>
                        <tr>
                            <th colspan="7" class="text-center medal"><i class="fas fa-medal gold"></i></th>
                        </tr>
                        <tr>
                            <th colspan="7" class="text-center">
                                <h5>
                                    <span class="text-primary">Snelste wedstrijd:</span> <?= $fastestActivity->getName(); ?>
                                    <?= $fastestActivity->getStartDateLocal()->format('d-m-Y'); ?>
                                </h5>
                            </th>
                        </tr>
                        <tr>
                            <th class="text-center"><i class="fas fa-road"></i></th>
                            <th class="text-center"><i class="fas fa-tachometer-alt"></i></th>
                            <th class="text-center"><i class="fas fa-stopwatch"></i></th>
                            <th class="text-center"><i class="fas fa-heartbeat"></i></th>
                            <th class="text-center"><i class="fas fa-mountain"></i></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th class="text-center"><?= $this->stravaViewHelper()->getDistance($fastestActivity->getDistance()); ?>
                                km
                            </th>
                            <th class="text-center"><?= $this->stravaViewHelper()->getAverageSpeed($fastestActivity->getAverageSpeed()); ?></th>
                            <th class="text-center"><?= $this->stravaViewHelper()->getMovingTime($fastestActivity->getMovingTime()); ?></th>
                            <th class="text-center"><?= $fastestActivity->getAverageHeartrate(); ?></th>
                            <th class="text-center"><?= $this->stravaViewHelper()->getTotalElevationGain($fastestActivity->getTotalElevationGain()); ?></th>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col">
                <table class="table table-sm table-bordered table-hover table-striped">
                    <thead>
                        <tr>
                            <th colspan="7" class="text-center medal"><i class="fas fa-ruler brown"></i></th>
                        </tr>
                        <tr>
                            <th colspan="7" class="text-center">
                                <h5>
                                    <span class="text-primary">Langste wedstrijd:</span> <?= $longestActivity->getName(); ?>
                                    <?= $longestActivity->getStartDateLocal()->format('d-m-Y'); ?>
                                </h5>
                            </th>
                        </tr>
                        <tr>
                            <th class="text-center"><i class="fas fa-road"></i></th>
                            <th class="text-center"><i class="fas fa-tachometer-alt"></i></th>
                            <th class="text-center"><i class="fas fa-stopwatch"></i></th>
                            <th class="text-center"><i class="fas fa-heartbeat"></i></th>
                            <th class="text-center"><i class="fas fa-mountain"></i></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th class="text-center"><?= $this->stravaViewHelper()->getDistance($longestActivity->getDistance()); ?>
                                km
                            </th>
                            <th class="text-center"><?= $this->stravaViewHelper()->getAverageSpeed($longestActivity->getAverageSpeed()); ?></th>
                            <th class="text-center"><?= $this->stravaViewHelper()->getMovingTime($longestActivity->getMovingTime()); ?></th>
                            <th class="text-center"><?= $longestActivity->getAverageHeartrate(); ?></th>
                            <th class="text-center"><?= $this->stravaViewHelper()->getTotalElevationGain($longestActivity->getTotalElevationGain()); ?></th>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="row mt-3">
            <div class="col">
                <table class="table table-sm table-bordered table-hover table-striped">
                    <thead>
                    <tr>
                        <th class="text-center medal"><i class="fas fa-stopwatch darkBlue"></i></th>
                    </tr>
                    <tr>
                        <th class="text-center">
                            <h5>
                                <span class="text-primary">Snelste wedstrijd 1 km:</span> <?= $fastestRound->getActivity()->getName(); ?>
                                <?= $fastestRound->getActivity()->getStartDateLocal()->format('d-m-Y'); ?>
                            </h5>
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td class="text-center"><?= $this->stravaViewHelper()->getAverageSpeed($fastestRound->getAverageSpeed()); ?></td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>