<div class="row mt-3">
    <h3 class="col text-center">
        Wedstrijd feiten feiten
    </h3>
</div>
<div class="row mt-3">
    <div class="col">
        <table class="table table-dark table-sm table-bordered table-hover table-striped">
            <thead class="thead-dark">
            <tr>
                <th colspan="7" class="text-center medal"><i class="fas fa-medal gold"></i></th>
            </tr>
            <tr>
                <th colspan="7" class="text-center">
                    <h5>Snelste wedstrijd<br/><?= $fastestActivity->getName(); ?></h5>
                    <h7><?= $fastestActivity->getStartDateLocal()->format('d-m-Y'); ?></h7>
                </th>
            </tr>
            <tr>
                <th class="text-center"><i class="fas fa-road"></i></th>
                <th class="text-center"><i class="fas fa-tachometer-alt"></i></th>
                <th class="text-center"><i class="fas fa-stopwatch"></i></th>
                <th class="text-center"><i class="fas fa-heartbeat"></i></th>
                <th class="text-center"><i class="fas fa-mountain"></i></th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <th class="text-center"><?= $this->stravaViewHelper()->getDistance($fastestActivity->getDistance()); ?> km</th>
                <th class="text-center"><?= $this->stravaViewHelper()->getAverageSpeed($fastestActivity->getAverageSpeed()); ?></th>
                <th class="text-center"><?= $this->stravaViewHelper()->getMovingTime($fastestActivity->getMovingTime()); ?></th>
                <th class="text-center"><?= $fastestActivity->getAverageHeartrate(); ?></th>
                <th class="text-center"><?= $this->stravaViewHelper()->getTotalElevationGain($fastestActivity->getTotalElevationGain()); ?></th>
            </tr>
            </tbody>
        </table>
    </div>
</div>
<div class="row mt-3">
    <div class="col">
        <table class="table table-dark table-sm table-bordered table-hover table-striped">
            <thead class="thead-dark">
            <tr>
                <th colspan="7" class="text-center medal"><i class="fas fa-ruler brown"></i></th>
            </tr>
            <tr>
                <th colspan="7" class="text-center">
                    <h5>Langste wedstrijd<br/><?= $longestActivity->getName(); ?></h5>
                    <h7><?= $longestActivity->getStartDateLocal()->format('d-m-Y'); ?></h7>
                </th>
            </tr>
            <tr>
                <th class="text-center"><i class="fas fa-road"></i></th>
                <th class="text-center"><i class="fas fa-tachometer-alt"></i></th>
                <th class="text-center"><i class="fas fa-stopwatch"></i></th>
                <th class="text-center"><i class="fas fa-heartbeat"></i></th>
                <th class="text-center"><i class="fas fa-mountain"></i></th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <th class="text-center"><?= $this->stravaViewHelper()->getDistance($longestActivity->getDistance()); ?> km</th>
                <th class="text-center"><?= $this->stravaViewHelper()->getAverageSpeed($longestActivity->getAverageSpeed()); ?></th>
                <th class="text-center"><?= $this->stravaViewHelper()->getMovingTime($longestActivity->getMovingTime()); ?></th>
                <th class="text-center"><?= $longestActivity->getAverageHeartrate(); ?></th>
                <th class="text-center"><?= $this->stravaViewHelper()->getTotalElevationGain($longestActivity->getTotalElevationGain()); ?></th>
            </tr>
            </tbody>
        </table>
    </div>
</div>

<div class="row mt-3">
    <div class="col">
        <table class="table table-dark table-sm table-bordered table-hover table-striped">
            <thead class="thead-dark">
            <tr>
                <th class="text-center medal"><i class="fas fa-stopwatch darkBlue"></i></th>
            </tr>
            <tr>
                <th class="text-center">
                    <h5>Snelste wedstrijd 1 km<br/><?= $fastestRound->getActivity()->getName(); ?></h5>
                    <h7><?= $fastestRound->getActivity()->getStartDateLocal()->format('d-m-Y'); ?></h7>
                </th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td class="text-center"><?= $this->stravaViewHelper()->getAverageSpeed($fastestRound->getAverageSpeed()); ?></td>
            </tr>
            </tbody>
        </table>
    </div>
</div>