<?php
$this->mainMenu()->setActiveItemId('importstrava');
$this->pageBreadcrumbs()->setLayout('beheer');
$this->pageBreadcrumbs()->setItems([
    'Beheer' => $this->url('beheer'),
    'Strava Log' => $this->url('stravalog'),
]);
?>
<!-- Page Header -->
<div class="row">
    <h1 class="col">STRAVA LOG</h1>
</div>
<!-- Breadcrumbs -->
<div class="row">
    <div class="col">
        <?= $this->pageBreadcrumbs()->render(); ?>
    </div>
</div>
<div class="row">
    <div class="col">
        <table class="table table-dark table-sm table-bordered table-hover table-striped">
            <thead class="thead-dark">
            <tr>
                <th>#</th>
                <th>Import date</th>
                <th>Total imports</th>
                <th class="text-center"><i class="fas fa-cogs"></i></th>
            </tr>
            </thead>
            <tbody>
            <?php $totalImports = 0; ?>
            <?php foreach ($items AS $index => $item) { ?>
                <?php $nr = $index + 1; ?>
                <tr id="importLogItem<?= $item->getId(); ?>">
                    <td><?= $nr; ?></td>
                    <td><?= $item->getImportDate()->format('Y-m-d H:i:s'); ?></td>
                    <th><?= $totalActivities = count($item->getActivities()) ?></th>
                    <td class="text-center">
                        <?php if ($index === 0) { ?>
                            <button type="button" data-importid="<?= $item->getId() ?>"
                                    class="btn btn-sm btn-danger removeImport" data-toggle="modal"
                                    data-target="#confirmationModal">
                                <i class="fas fa-undo"></i>
                            </button>
                        <?php } ?>
                    </td>
                </tr>
                <?php $totalImports = $totalImports + $totalActivities; ?>

            <?php } ?>
            <tr>
                <th colspan="2" class="text-right">Totaal</th>
                <th colspan="2"><?= $totalImports ?></th>
            </tr>
            </tbody>
        </table>
    </div>
</div>
<!-- Confirmation Modal -->
<div class="modal" id="confirmationModal">
    <div class="modal-dialog">
        <div class="modal-content bg-dark">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Import terugdraaien</h4>
                <button type="button" class="close text-white" data-dismiss="modal">&times;</button>
            </div>
            <!-- Modal body -->
            <div class="modal-body">
                Weet u zeker dat u de import wilt verwijderen. U zult opnieuw de data moeten importeren.
            </div>
            <!-- Modal footer -->
            <div class="modal-footer">
                <button class="btn btn-sm btn-danger" id="removeLog" data-removelogid="">
                    Verwijder <i class="fas fa-trash-alt"></i>
                </button>
                <button type="button" class="btn btn-sm btn-warning" data-dismiss="modal">
                    Annuleer <i class="far fa-window-close"></i>
                </button>
            </div>

        </div>
    </div>
</div>
<!-- End Confirmation Modal -->

<script>
    $('button.removeImport').click(function () {
        var importId = $(this).data('importid');
        $('button#removeLog').data('removelogid', importId);
    });

    $('button#removeLog').click(function () {
        var removelogId = $(this).data('removelogid');

        if (removelogId != '') {
            $.ajax({
                type: 'POST',
                data: {
                    removelogId: removelogId
                },
                url: "<?= $this->url('beheer/stravalog', ['action' => 'removeImport']); ?>",
                async: true,
                success: function (data) {
                    if (data.success === true) {
                        $('#confirmationModal').modal('hide')
                        $('tr#importLogItem' + data.removelogId).slideUp( "slow", function() {
                            // Animation complete.
                        });
                    } else {
                        alert(data.errorMessage);
                    }
                }
            });
        }
    });

</script>
